# Generated by Django 4.2.7 on 2025-10-19 13:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swapi_id', models.IntegerField(help_text='ID from SWAPI', unique=True)),
                ('title', models.CharField(max_length=200)),
                ('episode_id', models.IntegerField()),
                ('opening_crawl', models.TextField()),
                ('director', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['release_date'],
                'indexes': [models.Index(fields=['release_date'], name='films_film_release_ae2462_idx'), models.Index(fields=['swapi_id'], name='films_film_swapi_i_1c5f63_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Maximum 500 characters', max_length=500, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('author_name', models.CharField(default='Anonymous', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='films.film')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['film', 'created_at'], name='films_comme_film_id_491294_idx')],
            },
        ),
    ]
